### ISSUE TITLE
EXC_BAD_ACCESS in convertConfig

### ISSUE THREAD

**Issue by vikramgupta** [nolanbrown/Tesseract-iPhone-Demo#1]
Hi, I am experimenting a few things with the OCR demo application. It is crashing in "ocrimage" function on calling "tess->tesseractRect" after I select any image from image picker. This is happening every time. I am trying to debug the issue, but posting here also, just in case you have any idea about this. I am using iphone simulator 3.1, sdk and xcode version 3.1.4

Thanks,
Vikram

**Comment by jelan** [comment]
Hi

I am experiencing the same problem. Did you manage to solve the problem? 
I am using Xcode 3.2.5 and ran the OCR demo app on iPhone 4 with iOS 4.2.

Thanks
Jelan

**Comment by vikramgupta** [comment]
@jelan, No I couldn't solve it. :(

**Comment by alexprest** [comment]
Same problem here.. Hope Nolan will shed some light on this issue..
